// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Deportes.DAL.Api.Entities;
using Microsoft.EntityFrameworkCore;

namespace Deportes.DAL.Api;

public partial class DeportesContext : DbContext
{
    public DeportesContext(DbContextOptions<DeportesContext> options)
        : base(options)
    {
    }

    public virtual DbSet<bitacora_certificacion> bitacora_certificacion { get; set; }

    public virtual DbSet<cliente> cliente { get; set; }

    public virtual DbSet<detalle_factura> detalle_factura { get; set; }

    public virtual DbSet<factura> factura { get; set; }

    public virtual DbSet<producto> producto { get; set; }

    public virtual DbSet<rol> rol { get; set; }

    public virtual DbSet<usuario> usuario { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb4_spanish_ci");

        modelBuilder.Entity<bitacora_certificacion>(entity =>
        {
            entity.HasKey(e => e.id_bitacora).HasName("PRIMARY");

            entity.Property(e => e.fecha_evento).HasDefaultValueSql("CURRENT_TIMESTAMP");

            entity.HasOne(d => d.id_facturaNavigation).WithMany(p => p.bitacora_certificacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_bitacora_factura");

            entity.HasOne(d => d.id_usuarioNavigation).WithMany(p => p.bitacora_certificacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_bitacora_usuario");
        });

        modelBuilder.Entity<cliente>(entity =>
        {
            entity.HasKey(e => e.id_cliente).HasName("PRIMARY");

            entity.Property(e => e.activo).HasDefaultValueSql("b'1'");
            entity.Property(e => e.actualizado_en)
                .ValueGeneratedOnAddOrUpdate()
                .HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.creado_en).HasDefaultValueSql("CURRENT_TIMESTAMP");
        });

        modelBuilder.Entity<detalle_factura>(entity =>
        {
            entity.HasKey(e => e.id_detalle).HasName("PRIMARY");

            entity.Property(e => e.actualizado_en)
                .ValueGeneratedOnAddOrUpdate()
                .HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.creado_en).HasDefaultValueSql("CURRENT_TIMESTAMP");

            entity.HasOne(d => d.id_facturaNavigation).WithMany(p => p.detalle_factura).HasConstraintName("fk_detalle_factura");

            entity.HasOne(d => d.id_productoNavigation).WithMany(p => p.detalle_factura).HasConstraintName("fk_detalle_producto");
        });

        modelBuilder.Entity<factura>(entity =>
        {
            entity.HasKey(e => e.id_factura).HasName("PRIMARY");

            entity.Property(e => e.actualizado_en)
                .ValueGeneratedOnAddOrUpdate()
                .HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.creado_en).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.eliminado).HasDefaultValueSql("b'0'");

            entity.HasOne(d => d.id_cliente_emisorNavigation).WithMany(p => p.facturaid_cliente_emisorNavigation)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_factura_emisor");

            entity.HasOne(d => d.id_cliente_receptorNavigation).WithMany(p => p.facturaid_cliente_receptorNavigation)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_factura_receptor");

            entity.HasOne(d => d.id_usuarioNavigation).WithMany(p => p.factura)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_factura_usuario");
        });

        modelBuilder.Entity<producto>(entity =>
        {
            entity.HasKey(e => e.id_producto).HasName("PRIMARY");

            entity.Property(e => e.activo).HasDefaultValueSql("b'1'");
            entity.Property(e => e.actualizado_en)
                .ValueGeneratedOnAddOrUpdate()
                .HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.creado_en).HasDefaultValueSql("CURRENT_TIMESTAMP");
        });

        modelBuilder.Entity<rol>(entity =>
        {
            entity.HasKey(e => e.id_rol).HasName("PRIMARY");

            entity.Property(e => e.actualizado_en)
                .ValueGeneratedOnAddOrUpdate()
                .HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.creado_en).HasDefaultValueSql("CURRENT_TIMESTAMP");
        });

        modelBuilder.Entity<usuario>(entity =>
        {
            entity.HasKey(e => e.id_usuario).HasName("PRIMARY");

            entity.Property(e => e.activo).HasDefaultValueSql("b'1'");
            entity.Property(e => e.actualizado_en)
                .ValueGeneratedOnAddOrUpdate()
                .HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.creado_en).HasDefaultValueSql("CURRENT_TIMESTAMP");

            entity.HasOne(d => d.id_rolNavigation).WithMany(p => p.usuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_usuario_rol");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}