// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Deportes.DAL.Api.Entities;

[Index("id_factura", Name = "fk_bitacora_factura")]
[Index("id_usuario", Name = "fk_bitacora_usuario")]
public partial class bitacora_certificacion
{
    [Key]
    public int id_bitacora { get; set; }

    public int id_factura { get; set; }

    public byte tipo_evento { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime fecha_evento { get; set; }

    public int id_usuario { get; set; }

    [StringLength(255)]
    public string comentario { get; set; }

    [ForeignKey("id_factura")]
    [InverseProperty("bitacora_certificacion")]
    public virtual factura id_facturaNavigation { get; set; }

    [ForeignKey("id_usuario")]
    [InverseProperty("bitacora_certificacion")]
    public virtual usuario id_usuarioNavigation { get; set; }
}