// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Deportes.DAL.Api.Entities;

[Index("nit", Name = "nit", IsUnique = true)]
public partial class cliente
    {
        [Key]
        public int id_cliente { get; set; }

        [Required]
        [StringLength(20)]
        public string nit { get; set; }

        [Required]
        [StringLength(100)]
        public string nombre { get; set; }

        [StringLength(200)]
        public string direccion { get; set; }

        [Column(TypeName = "bit(1)")]
        public ulong activo { get; set; }

        [Column(TypeName = "timestamp")]
        public DateTime creado_en { get; set; }

        [Column(TypeName = "timestamp")]
        public DateTime actualizado_en { get; set; }

        [InverseProperty("id_cliente_emisorNavigation")]
        public virtual ICollection<factura> facturaid_cliente_emisorNavigation { get; set; } = new List<factura>();

        [InverseProperty("id_cliente_receptorNavigation")]
        public virtual ICollection<factura> facturaid_cliente_receptorNavigation { get; set; } = new List<factura>();
}