// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Deportes.DAL.Api.Entities;

[Index("id_producto", Name = "fk_detalle_producto")]
[Index("id_factura", Name = "idx_detalle_factura")]
public partial class detalle_factura
{
    [Key]
    public int id_detalle { get; set; }

    public int id_factura { get; set; }

    public int? id_producto { get; set; }

    [Required]
    [StringLength(255)]
    public string descripcion { get; set; }

    public int cantidad { get; set; }

    [Precision(12, 2)]
    public decimal precio_unitario { get; set; }

    [Precision(12, 2)]
    public decimal descuento { get; set; }

    [Precision(12, 2)]
    public decimal subtotal { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime creado_en { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime actualizado_en { get; set; }

    [ForeignKey("id_factura")]
    [InverseProperty("detalle_factura")]
    public virtual factura id_facturaNavigation { get; set; }

    [ForeignKey("id_producto")]
    [InverseProperty("detalle_factura")]
    public virtual producto id_productoNavigation { get; set; }
}