// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Deportes.DAL.Api.Entities;

[Index("id_cliente_emisor", Name = "fk_factura_emisor")]
[Index("id_cliente_receptor", Name = "fk_factura_receptor")]
[Index("id_usuario", Name = "fk_factura_usuario")]
[Index("fecha_emision", Name = "idx_factura_fecha")]
[Index("numero_autorizacion", Name = "numero_autorizacion", IsUnique = true)]
[Index("uuid", Name = "uuid", IsUnique = true)]
[Index("serie", "correlativo", Name = "ux_factura_serie_correlativo", IsUnique = true)]
public partial class factura
{
    [Key]
    public int id_factura { get; set; }

    public Guid uuid { get; set; }

    public int id_cliente_emisor { get; set; }

    public int id_cliente_receptor { get; set; }

    public int id_usuario { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime fecha_emision { get; set; }

    public byte estado { get; set; }

    [Column(TypeName = "bit(1)")]
    public ulong eliminado { get; set; }

    [Precision(12, 2)]
    public decimal subtotal { get; set; }

    [Precision(12, 2)]
    public decimal total { get; set; }

    [StringLength(255)]
    public string observaciones { get; set; }

    [StringLength(50)]
    public string numero_autorizacion { get; set; }

    [StringLength(10)]
    public string serie { get; set; }

    public int? correlativo { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fecha_certificacion { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime creado_en { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime actualizado_en { get; set; }

    [InverseProperty("id_facturaNavigation")]
    public virtual ICollection<bitacora_certificacion> bitacora_certificacion { get; set; } = new List<bitacora_certificacion>();

    [InverseProperty("id_facturaNavigation")]
    public virtual ICollection<detalle_factura> detalle_factura { get; set; } = new List<detalle_factura>();

    [ForeignKey("id_cliente_emisor")]
    [InverseProperty("facturaid_cliente_emisorNavigation")]
    public virtual cliente id_cliente_emisorNavigation { get; set; }

    [ForeignKey("id_cliente_receptor")]
    [InverseProperty("facturaid_cliente_receptorNavigation")]
    public virtual cliente id_cliente_receptorNavigation { get; set; }

    [ForeignKey("id_usuario")]
    [InverseProperty("factura")]
    public virtual usuario id_usuarioNavigation { get; set; }
}