// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Deportes.DAL.Api.Entities;

[Index("sku", Name = "sku", IsUnique = true)]
public partial class producto
{
    [Key]
    public int id_producto { get; set; }

    [StringLength(50)]
    public string sku { get; set; }

    [Required]
    [StringLength(100)]
    public string nombre { get; set; }

    [Column(TypeName = "text")]
    public string descripcion { get; set; }

    [Precision(12, 2)]
    public decimal precio_unitario { get; set; }

    public int cantidad { get; set; }

    [Column(TypeName = "bit(1)")]
    public ulong activo { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime creado_en { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime actualizado_en { get; set; }

    [InverseProperty("id_productoNavigation")]
    public virtual ICollection<detalle_factura> detalle_factura { get; set; } = new List<detalle_factura>();
}