// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Deportes.DAL.Api.Entities;

[Index("nombre", Name = "nombre", IsUnique = true)]
public partial class rol
{
    [Key]
    public int id_rol { get; set; }

    [Required]
    [StringLength(50)]
    public string nombre { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime creado_en { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime actualizado_en { get; set; }

    [InverseProperty("id_rolNavigation")]
    public virtual ICollection<usuario> usuario { get; set; } = new List<usuario>();
}