// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Deportes.DAL.Api.Entities;

[Index("id_rol", Name = "fk_usuario_rol")]
[Index("nombre_usuario", Name = "nombre_usuario", IsUnique = true)]
public partial class usuario
{
    [Key]
    public int id_usuario { get; set; }

    [Required]
    [StringLength(100)]
    public string nombre_usuario { get; set; }

    [Required]
    [StringLength(255)]
    public string password_hash { get; set; }

    public int id_rol { get; set; }

    [Column(TypeName = "bit(1)")]
    public ulong activo { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime creado_en { get; set; }

    [Column(TypeName = "timestamp")]
    public DateTime actualizado_en { get; set; }

    [InverseProperty("id_usuarioNavigation")]
    public virtual ICollection<bitacora_certificacion> bitacora_certificacion { get; set; } = new List<bitacora_certificacion>();

    [InverseProperty("id_usuarioNavigation")]
    public virtual ICollection<factura> factura { get; set; } = new List<factura>();

    [ForeignKey("id_rol")]
    [InverseProperty("usuario")]
    public virtual rol id_rolNavigation { get; set; }
}